###
GET http://localhost:8080/index

###
POST http://localhost:8080/card/addCard
Content-Type: application/json

{
  "name": "first-card",
  "description": "a test card",
  "imageUrl": "",
  "family": "fire",
  "affinity": "water",
  "hp": 100,
  "attack": 45,
  "defense": 30,
  "energy": 25
}


###

GET http://127.0.0.1:8080/card/
Accept: application/json

###

GET http://127.0.0.1:8080/addUser

###

GET http://127.0.0.1:8080/card/0
Accept: application/json

###

GET http://127.0.0.1:8080/test/0
Accept: application/json

###

